### PR TITLE
prep new release

### PR DESCRIPTION
**Pull request by MacFan4000**
I'm aware of the conflicts

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Fix the conflicts, compare CI config with MirahezeBots dev branch

**Comment by MacFan4000** [comment]
> Fix the conflicts, compare CI config with MirahezeBots dev branch

@RhinosF1 I don't want to fix the conflicts until we are ready to push to the release branch. If I do it now via git bash, it will push to release.

I copy pasted from the pingpong repo. I don't believe anything is missing?

**Comment by RhinosF1** [comment]
> > Fix the conflicts, compare CI config with MirahezeBots dev branch
> 
> @RhinosF1 I don't want to fix the conflicts until we are ready to push to the release branch. If I do it now via git bash, it will push to release.
> 
> I copy pasted from the pingpong repo. I don't believe anything is missing?

Use the dev branch on bots repo please

**Comment by MacFan4000** [comment]
> > > Fix the conflicts, compare CI config with MirahezeBots dev branch
> > 
> > 
> > @RhinosF1 I don't want to fix the conflicts until we are ready to push to the release branch. If I do it now via git bash, it will push to release.
> > I copy pasted from the pingpong repo. I don't believe anything is missing?
> 
> Use the dev branch on bots repo please

again I copied the ci stuff **directly** from the pingpong repo (currently release is up to date with dev). As far as I know, I copied all of the checks.

**Comment by RhinosF1** [comment]
I updated config yesterday. They're not.

**Comment by MacFan4000** [comment]
@RhinosF1 The other checks in the core repo are as follows
pytests - the layout is different is the core repo, sore more lines are needed in the ci
flake8 - again the layout is different so more lines were needed in the ci.
requirements - this plugin doesn't have any special requirements other then sopel, so I didn't see a need for that.

**Comment by RhinosF1** [comment]
Look at the 2 most recent commits

**Comment by MacFan4000** [comment]
@RhinosF1 ah, ok added

**Review by RhinosF1 — APPROVED** [review]
What about the code coverage disable but otherwise LGTM

**Comment by MacFan4000** [comment]
Ok, I'm going to fix the conflicts now, which will basically merge this PR.

**Comment by RhinosF1** [comment]
Ok

**Pull request merged**
